#!/bin/bash

# Check if the directory already exists
# MESHROOM is the main app
if [ -d ./meshroom ]
then
    echo "meshroom directory already exists"

# Otherwise, create a new one and start on downloading meshroom
else

    # Set up the url from which we download the meshroom package, the package
    # name and the output directory
    FILE="Meshroom-2021.1.0-linux-cuda10"
    URL="https://github.com/alicevision/meshroom/releases/download/v2021.1.0/$FILE.tar.gz"
    OUTPUT="meshroom"

    # Make the meshroom
    mkdir $OUTPUT

    # Download the file, extract the package into the output directory and
    # remove the old package
    curl -sL $URL | tar zxf - -C $OUTPUT --strip-components=1
fi
